### ISSUE TITLE
地震感知情報の表示判定: 判定基準検討

### ISSUE THREAD

**Issue by p2pquake-takuya** [p2pquake/epsp-peer-cs#97]
### P2P地震情報 for Peer (Beta 3)の判定基準

- リセット条件: 最後の地震感知情報受信から40秒以上が経過したとき

項目の定義

項目|算出方法
--|--
感知度|合計件数 / 1件目からの経過秒数
発信割合|合計件数 / ピア総数
地域発信割合|地域コード毎の発信割合 (発信件数 / ピア数) の最大値
大地域集中割合|地域コード上1桁毎の発信件数 / 合計件数 の最大値

※大地域: 北海道、東北、関東、北陸・甲信、東海・近畿、中国・四国、九州、沖縄 の7地域

判定基準（件数が3件以上のとき、いずれかを満たすこと）

判定基準|感知度|発信割合|地域発信割合|大地域集中割合
--|--|--|--|--
1|>= 0.25|--|>= 5%|--
2|>= 0.15|--|>= 30%|--
3|--|>= 1%|>= 3.5%|--
4|--|>= 0.6%|>= 4%|100%
5|>= 0.18|--|>= 4%|100%

表示レベル|係数 (※判定基準に適用)
--|--
1|0.875
2|1.0
3|1.2
4|1.4

### 精度評価基準

- リセット条件は変えないものとする

項目|算出方法
--|--
true positive|表示基準を満たし、かつ有効な情報
false positive|表示基準を満たしたが、無効な情報
true negative|表示基準を満たさないが、有効な情報
false negative|表示基準を満たさず、かつ無効な情報
経過時間|表示判断した時間（1件目からの経過秒数）

**地震感知情報の単位**

- リセット条件に合致するまでの1件以上の累積情報

**地震感知情報の有効性判定方法**

下記をすべて満たすこと

1. 地震情報の発生日時が、地震感知情報の発信時間帯±2分である
1. 地震情報の震度1以上を観測した都道府県が、地震感知情報の発信都道府県に含まれる

**Comment by p2pquake-takuya** [comment]
対象: 2017/10/01〜2018/09/30

種類|レベル|TP|FP|TN|FN|Accuracy|ErrorRate|Precision|Sensitivity|Specificity|FalsePositiveRate|FalseNegativeRate
--|--|--|--|--|--|--|--|--|--|--|--|--
現行判定基準|1|370|211|3013|261|0.87756|0.12244|0.63683|0.58637|0.93455|0.06545|0.41363
現行判定基準|2|342|190|3034|289|0.87575|0.12425|0.64286|0.54200|0.94107|0.05893|0.45800
現行判定基準|3|312|159|3065|319|0.87601|0.12399|0.66242|0.49445|0.95068|0.04932|0.50555
現行判定基準|4|292|139|3085|339|0.87601|0.12399|0.67749|0.46276|0.95689|0.04311|0.53724

**Comment by p2pquake-takuya** [comment]
2017/10/01〜2018/09/31

Class|Args|TP|FP|TN|FN|Accuracy|ErrorRate|Precision|Sensitivity|Specificity|FPRate|FNRate
--|--|--:|--:|--:|--:|--:|--:|--:|--:|--:|--:|--:
旧基準|1|318|153|3114|336|0.87529|0.12471|0.67516|0.48624|0.95317|0.04683|0.51376
旧基準|2|293|132|3135|361|0.87427|0.12573|0.68941|0.44801|0.95960|0.04040|0.55199
旧基準|3|266|119|3148|388|0.87070|0.12930|0.69091|0.40673|0.96358|0.03642|0.59327
旧基準|4|249|106|3161|405|0.86968|0.13032|0.70141|0.38073|0.96755|0.03245|0.61927

**Comment by p2pquake-takuya** [comment]
2017/10/01〜2018/09/31

Class|Args|TP|FP|TN|FN|Accuracy|ErrorRate|Precision|Sensitivity|Specificity|FPRate|FNRate
--|--|--:|--:|--:|--:|--:|--:|--:|--:|--:|--:|--:
旧基準|1|318|153|3114|336|0.87529|0.12471|0.67516|0.48624|0.95317|0.04683|0.51376
旧基準|2|293|132|3135|361|0.87427|0.12573|0.68941|0.44801|0.95960|0.04040|0.55199
旧基準|3|266|119|3148|388|0.87070|0.12930|0.69091|0.40673|0.96358|0.03642|0.59327
旧基準|4|249|106|3161|405|0.86968|0.13032|0.70141|0.38073|0.96755|0.03245|0.61927

**Comment by typewriter** [comment]
評価期間不明

Class | Args | TP | FP | TN | FN | Accuracy | ErrorRate | Precision | Sensitivity | Specificity | FPRate | FNRate
-- | -- | --: | --: | --: | --: | --: | --: | --: | --: | --: | --: | --:
旧基準 | 1 | 390 | 12 | 3223 | 408 | 0.89586 | 0.10414 | 0.97015 | 0.48872 | 0.99629 | 0.00371 | 0.51128
旧基準 | 2 | 360 | 12 | 3223 | 438 | 0.88842 | 0.11158 | 0.96774 | 0.45113 | 0.99629 | 0.00371 | 0.54887
旧基準 | 3 | 326 | 10 | 3225 | 472 | 0.88049 | 0.11951 | 0.97024 | 0.40852 | 0.99691 | 0.00309 | 0.59148
旧基準 | 4 | 302 | 6 | 3229 | 496 | 0.87553 | 0.12447 | 0.98052 | 0.37845 | 0.99815 | 0.00185 | 0.62155
RandomJudge | (*1) | 359 | 12 | 3223 | 439 | 0.88817 | 0.11183 | 0.96765 | 0.44987 | 0.99629 | 0.00371 | 0.55013
RandomJudge | (*2) | 326 | 7 | 3228 | 472 | 0.88123 | 0.11877 | 0.97898 | 0.40852 | 0.99784 | 0.00216 | 0.59148
RandomJudge | (*3) | 316 | 6 | 3229 | 482 | 0.879 | 0.121 | 0.98137 | 0.39599 | 0.99815 | 0.00185 | 0.60401

(*1) 0.25846/7/0.05271/0.39161/2.45335;0.00553/1/0.00167/0.36538/0.14725;0.04611/3/0.06169/0.75557/3.33789;0.19550/4/0.00433/0.23109/0.55814
(*2) 0.03404/7/0.00170/0.52033/0.10348;0.73981/2/0.02593/0.01443/0.46976
(*3) 0.00351/2/0.00289/0.58720/0.02634

※RandomJudgeはランダムサーチ。パラメタは 地域発信割合/件数/発信割合/大地域集中割合/感知度 、複数の場合セミコロン区切り
